// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	qa "question-answer/internal/domain/qa"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateAnswer provides a mock function with given fields: a
func (_m *Service) CreateAnswer(a qa.Answer) (uint64, error) {
	ret := _m.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAnswer")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(qa.Answer) (uint64, error)); ok {
		return rf(a)
	}
	if rf, ok := ret.Get(0).(func(qa.Answer) uint64); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(qa.Answer) error); ok {
		r1 = rf(a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateQuestion provides a mock function with given fields: q
func (_m *Service) CreateQuestion(q qa.Question) (*qa.Question, error) {
	ret := _m.Called(q)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuestion")
	}

	var r0 *qa.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(qa.Question) (*qa.Question, error)); ok {
		return rf(q)
	}
	if rf, ok := ret.Get(0).(func(qa.Question) *qa.Question); ok {
		r0 = rf(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qa.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(qa.Question) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAnswer provides a mock function with given fields: id
func (_m *Service) DeleteAnswer(id uint64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteQuestion provides a mock function with given fields: id
func (_m *Service) DeleteQuestion(id uint64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllQuestions provides a mock function with no fields
func (_m *Service) GetAllQuestions() ([]qa.Question, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllQuestions")
	}

	var r0 []qa.Question
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]qa.Question, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []qa.Question); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qa.Question)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAnswer provides a mock function with given fields: id
func (_m *Service) GetAnswer(id uint64) (*qa.Answer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAnswer")
	}

	var r0 *qa.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*qa.Answer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *qa.Answer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qa.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuestionWithAnswers provides a mock function with given fields: id
func (_m *Service) GetQuestionWithAnswers(id uint64) (*qa.Question, []qa.Answer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionWithAnswers")
	}

	var r0 *qa.Question
	var r1 []qa.Answer
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64) (*qa.Question, []qa.Answer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *qa.Question); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qa.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) []qa.Answer); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]qa.Answer)
		}
	}

	if rf, ok := ret.Get(2).(func(uint64) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
